Fix: allow inserting columns out of schema definition order
Fixes #30.

The issue was due to evaluating the values to be inserted. The cols
specified were not being taken in to account. Instead we just indexed
the table schema by value index.

This also fixes a nasty side effect. You could specify params out of
order but pass values in the schema order. This should be an error but
was accepted and led to a corrupted row being written.

Testing:

```
CREATE TABLE t (id INTEGER PRIMARY KEY, x VARCHAR(10));
insert into t(id, x) values (0, 'foo');
select * from t;
insert into t(id, x) values (1, 'bar');
select * from t;
insert into t(x, id) values ('baz', 2);
select * from t;
0|foo
0|foo
1|bar
0|foo
1|bar
2|baz
skdb> insert into t(x, id, foo) values ('baz', 2);
insert into t(x, id, foo) values ('baz', 2);
^
|
 ----- ERROR
Error: line 1, characters 0-0:
Value size mismatch
skdb> insert into t(x, id, foo) values ('baz', 2, 2);
insert into t(x, id, foo) values ('baz', 2, 2);
^
|
 ----- ERROR
Error: line 1, characters 0-0:
Column not found: foo
skdb> insert into t(x, id) values ('baz', 2, 2);
insert into t(x, id) values ('baz', 2, 2);
^
|
 ----- ERROR
Error: line 1, characters 0-0:
Value size mismatch with specified columns
skdb> insert into t(x, id) values (3, 'baz');
insert into t(x, id) values (3, 'baz');
^
|
 ----- ERROR
Error: line 1, characters 0-0:
Type mismatch on column 2 expected type STRING (found SKSQL.VInt(3))
```