[skdb] Fix ambiguous name for duplicate anonymous table.
Fixes
```
skdb> SELECT * FROM (SELECT 1), (SELECT 1)
SELECT * FROM (SELECT 1), (SELECT 1)
^
|
 ----- ERROR
Error: line 1, characters 0-0:
Ambiguous name: /select_-3436902621689144249/.col<0>
```

caused by both `(SELECT 1)` sub-queries having the same hash, and no
explicit name, leading to the expansion of `*` being
ambiguous (`/select_-3436902621689144249/.col<0>`,
           `/select_-3436902621689144249/.col<0>`).

The fix involves using the table's index in the `FROM` clause to
generate a unique table name for non-aliased anonymous tables.